### ISSUE TITLE
Secure tests not working for activerecord, sqlalchemy, gorm

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/examples-orms#117]
Haven't triaged yet. Example failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=2202492&buildTypeId=Cockroach_ExampleORMs&tab=buildLog#_state=1680,1195

I will skip the secure tests for now, so this issue will track unskipping them.

**Comment by tbg** [comment]
I switched gorm back to secure but can't reproduce a failure in multiple runs of

```
go test -v -count 10 -failfast -run GORM ./testing/ -cockroach-binary=../cockroach.linux-gnu-amd64.LATEST; echo $?
```

**Comment by tbg** [comment]
Aha - I downloaded the cockroach artifact from that particular run, and voila:

```
$ go test -v -count 10 -failfast -run GORM ./testing/ -cockroach-binary ~/Downloads/cockroach ; echo $?
=== RUN   TestGORM
2020/08/21 10:42:04 Using custom cockroach binary: /home/tobias/Downloads/cockroach
2020/08/21 10:42:04 process 289011 started: /home/tobias/Downloads/cockroach start-single-node --logtostderr --certs-dir=/tmp/cockroach-testserver136264212/certs --host=localhost --port=0 --http-port=0 --store=/tmp/cockroach-testserver136264212 --listening-url-file=/tmp/cockroach-testserver136264212/listen-url
--- FAIL: TestGORM (1.08s)
    main_test.go:253: exit status 1
FAIL
FAIL	github.com/cockroachdb/examples-orms/testing	1.081s
FAIL
1
```

**Comment by tbg** [comment]
I think I know what this is. We try to run the tenancy test cases whenever we see a 20.2-alpha version, but with the changes of the cert, one really needs to have picked up https://github.com/cockroachdb/cockroach/pull/52508.
