### ISSUE TITLE
Python Asyncpg

### ISSUE THREAD

**Issue by kszucs** [cockroachdb/examples-orms#19]
I'm trying to use cockroach with [asyncpg](https://github.com/MagicStack/asyncpg).

With [plain connection](https://magicstack.github.io/asyncpg/current/api/index.html#connection) it works like a charm. On the other hand using [connection pool](https://magicstack.github.io/asyncpg/current/api/index.html#connection-pool) fails with the following error:

```
ERROR:sanic:Traceback (most recent call last):
  File "/Users/krisz/.pyenv/versions/miniconda3-latest/envs/ml3/lib/python3.6/site-packages/sanic/app.py", line 391, in handle_request
    response = await response
  File "/Users/krisz/Workspace/papi/papi/app.py", line 34, in accounts_create
    print(results)
  File "/Users/krisz/.pyenv/versions/miniconda3-latest/envs/ml3/lib/python3.6/site-packages/asyncpg/pool.py", line 257, in __aexit__
    await self.pool.release(con)
  File "/Users/krisz/.pyenv/versions/miniconda3-latest/envs/ml3/lib/python3.6/site-packages/asyncpg/pool.py", line 189, in release
    await connection.reset()
  File "/Users/krisz/.pyenv/versions/miniconda3-latest/envs/ml3/lib/python3.6/site-packages/asyncpg/connection.py", line 412, in reset
    ''')
  File "/Users/krisz/.pyenv/versions/miniconda3-latest/envs/ml3/lib/python3.6/site-packages/asyncpg/connection.py", line 171, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 255, in query (asyncpg/protocol/protocol.c:56799)
asyncpg.exceptions.InternalServerError: syntax error at or near "DO"
```

Caused by the [resetting the connection](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/connection.py#L396) :

```python
await self.execute('''
            DO $$
            BEGIN
                PERFORM * FROM pg_listening_channels() LIMIT 1;
                IF FOUND THEN
                    UNLISTEN *;
                END IF;
            END;
            $$;
            SET SESSION AUTHORIZATION DEFAULT;
            RESET ALL;
            CLOSE ALL;
            SELECT pg_advisory_unlock_all();
        ''')
```

I don't know the exact solution, but I'd like to use Cockroach with asyncpg :)

**Comment by tamird** [comment]
Looks like asyncpg is using plpgsql, which we do not support. See https://www.postgresql.org/docs/9.6/static/sql-do.html.

Also seems like that query wants to use PG notifications, which we also do not support.

**Comment by kszucs** [comment]
Could You recommend a workaround or "dialect" which could be implemented on asyncpg's side?

**Comment by kszucs** [comment]
It seems like Asyncpg is getting the default pg connector for async python due to recent popularity of sanic https://github.com/channelcat/sanic/blob/master/examples/sanic_asyncpg_example.py

I guess it would be beneficial for cockroach to support async python.

**Comment by kszucs** [comment]
I suggest to close this issue and help with asyncpg's https://github.com/MagicStack/asyncpg/issues/87
Thankfully both sides are responsive :)

**Comment by knz** [comment]
This `reset()` method is *entirely* dedicated to solving problems that do not (yet?) exist with cockroachdb. What it basically does is remove all open notifications channels and taken advisory locks. CockroachDB has neither.

My suggestion is to simply monkey-patch this method away from the class (replace it with a no-op) and see what happens.

**Comment by kszucs** [comment]
Great! Thank You!
