### ISSUE TITLE
TestDjango fails on release-v2.1

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/examples-orms#82]
TestDjango fails on release-v2.1. One example is https://teamcity.cockroachdb.com/viewLog.html?buildId=1572017&buildTypeId=Cockroach_UnitTests.

+cc https://github.com/cockroachdb/cockroach/issues/42083.

**Comment by rafiss** [comment]
We are not going to support Django with CockroachDB 2.1, so closing this. #93 makes it so only 2.1 and less is skipped, rather than all Django tests.
